### ISSUE TITLE
how to use this client ?

### ISSUE THREAD

**Issue by shenhequnying** [tsari/vpn-proxy#1]
i run in my docker container, the squid is running , and exec the vpn connection , it initiallize success.
but how to use these?
i use wget command add proxy variable, but it only keep the conn to proxy behind time out.
can you give me some way to use this ? thanks.

**Comment by shenhequnying** [comment]
the squid logs:
2015-12-02 02:39:34,766 WARN received SIGTERM indicating exit request
2015-12-02 02:39:34,766 INFO waiting for squid to die
2015-12-02 02:39:37,769 INFO waiting for squid to die
2015-12-02 02:39:40,773 INFO waiting for squid to die
2015-12-02 02:39:43,777 INFO waiting for squid to die
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2015-12-02 02:39:45,081 CRIT Supervisor running as root (no user in config file)
2015-12-02 02:39:45,081 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2015-12-02 02:39:45,397 INFO RPC interface 'supervisor' initialized
2015-12-02 02:39:45,397 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-12-02 02:39:45,397 INFO supervisord started with pid 1
2015-12-02 02:39:46,399 INFO spawned: 'squid' with pid 8
2015-12-02 02:39:47,406 INFO success: squid entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by shenhequnying** [comment]
this the vpn logs(some addr hide):
Wed Dec  2 03:49:46 2015 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)
Wed Dec  2 03:49:46 2015 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,route 172.17.0.1,topology net30,ping 10,ping-restart 120,ifconfig 172.17._._ 172.17._._'
Wed Dec  2 03:49:46 2015 OPTIONS IMPORT: timers and/or timeouts modified
Wed Dec  2 03:49:46 2015 OPTIONS IMPORT: --ifconfig/up options modified
Wed Dec  2 03:49:46 2015 OPTIONS IMPORT: route options modified
Wed Dec  2 03:49:46 2015 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Wed Dec  2 03:49:46 2015 ROUTE_GATEWAY 172._._._/255.255.0.0 IFACE=eth0 HWADDR=_:_:_:_:_:*
Wed Dec  2 03:49:46 2015 TUN/TAP device tun0 opened
Wed Dec  2 03:49:46 2015 TUN/TAP TX queue length set to 100
Wed Dec  2 03:49:46 2015 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Wed Dec  2 03:49:46 2015 /sbin/ip link set dev tun0 up mtu 1500
Wed Dec  2 03:49:46 2015 /sbin/ip addr add dev tun0 local 172.17._._ peer 172.17._._
Wed Dec  2 03:49:46 2015 /sbin/ip route add _._._._/32 via 172.17._._
Wed Dec  2 03:49:46 2015 /sbin/ip route del 0.0.0.0/0
Wed Dec  2 03:49:46 2015 /sbin/ip route add 0.0.0.0/0 via 172.17.0.*
Wed Dec  2 03:49:46 2015 /sbin/ip route add 172.17.0._/32 via 172.17.0._
Wed Dec  2 03:49:46 2015 Initialization Sequence Completed

**Comment by tsari** [comment]
Hi.

Please provide the access.log from the squid while trying to access a url via proxy.

`docker exec -it openvpn tail -f /var/log/squid3/access.log`

You could also try to wget the url from within the container to check if the vpn works fine.

**Comment by shenhequnying** [comment]
the vpn works fine , i can ensure, in the container the net worked though vpn.
and the server which run the container can use the proxy:containerip+3128.
but it can not use the original ip + 3128. 
that's why? it cause by the squid acl ? i have no idea.
thank you sir. your project is very suittable for my environment.

**Comment by shenhequnying** [comment]
i changed my acl config in squid.
the router in container changed.
0.0.0.0         172.17.0.9      0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
172.17.0.1      172.17.0.9      255.255.255.255 UGH   0      0        0 eth0
the iface changed from "tun0" to "eth0"

**Comment by tsari** [comment]
Sorry, but I only use this container on my private computer.
But I think if you run this on a server you might need a kind of port forwarding from your servers external port to the container port.

**Comment by shenhequnying** [comment]
thanks sir.
i will try to solve this problem : )

**Comment by shenhequnying** [comment]
i solved this problem....
but need to run two container else and the squid proxy is not required.
first run a nginx container use the openvpn net, then you need to link openvpn and nginx net and you need to run another nginx expose the port, then you can use the vpn net in any where!!!!!!!
